### ISSUE TITLE
Update the reference for documentation

### ISSUE THREAD

**Issue by greglucas** [SWxTREC/vector#18]
We moved the API over to its own repository, so now the most up-to-date API documentation is over there.
https://github.com/SWxTREC/vector-api
Should we link to that document instead of the current vector-code repository?
We would need to update this line:
https://github.com/SWxTREC/vector/blob/cab86dc5d01f481c269a65e03369e9df00928012/src/app/containers/docs/docs.component.html#L2

Of course, that is documentation of the API, not the calculation code... So, it depends on what documentation we actually want on the website.

**Comment by jennyknuth** [comment]
We could have both kinds of documentation on the website: calculator and api. The calculator documentation would be for people interested in running the calculator and understanding what that involves and what the results mean and the api documentation for people who want to run the calculator programmatically. What do you think?

**Comment by greglucas** [comment]
That'd be fine with me. I'm not sure how you'd want to lay that out in your webpage then though. Multiple headings and embed the links below them? I also don't have the documentation to the calculation code. That is currently just a link to the thesis I think.

**Comment by jennyknuth** [comment]
Under documentation there could be two tabs: calculator and api, and each tab would render (display) the appropriate markdown file.
